// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:timer_tracker_4029/src/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AchievementAdapter());
    registerAdapter(AchievementProgressAdapter());
    registerAdapter(BadgeAdapter());
    registerAdapter(HeartAdapter());
    registerAdapter(HeartCollectionAdapter());
    registerAdapter(HeartHistoryAdapter());
    registerAdapter(NavTutorialAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(UserAchievementAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AchievementAdapter());
    registerAdapter(AchievementProgressAdapter());
    registerAdapter(BadgeAdapter());
    registerAdapter(HeartAdapter());
    registerAdapter(HeartCollectionAdapter());
    registerAdapter(HeartHistoryAdapter());
    registerAdapter(NavTutorialAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(UserAchievementAdapter());
  }
}
